version: '3.8'

services:
  wordpress:
    image: wordpress
    container_name: wordpress-developer-setup-app
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress-plugin
      WORDPRESS_DB_PASSWORD: wordpress-plugin
      WORDPRESS_DB_NAME: wordpress-plugin
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes

  db:
    #uncomment these two lines for MySQL 5.7
    image: mysql:5.7.38

    #comment this line for MySQL 5.7
    #image: mysql:8.0.29
    container_name: wordpress-developer-setup-db
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress-plugin
      MYSQL_USER: wordpress-plugin
      MYSQL_PASSWORD: wordpress-plugin
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
